lib/features/home/screen/home_screen.dart
lib/features/home/widgets/best_goods_widget.dart
lib/features/home/widgets/best_movie_widget.dart
lib/features/home/widgets/box_office_ranking_widget.dart
lib/features/home/widgets/recommended_goods_widget.dart
lib/features/main/screen/main_screen.dart

메인 페이지 UI 제작
- M01
- 박스오피스 순위 위젯 생성
- 베스트 굿즈, 영화 위젯 생성
- 추천 굿즈 위젯 그리드 생성
- 정상 동작 여부 ( O )
- 공통 컴포넌트 제작 후 수정 예정

[M01] ui/M01

---

lib/features/favorite/screen/favorite_screen.dart
lib/features/favorite/widget/favorite_gridview.dart
lib/features/favorite/widget/item_type.dart
lib/widgets/goods_item.dart
lib/widgets/movie_item.dart
pubspec.lock

- f01
- f02
- 어떤 기능을 추가/수정했는지
- 정상 동작 여부 (O / X)
-

[f01/f02] 굿즈/영화 찜 목록 UI 구현

---

lib/widgets/common_tab_view.dart

- F01
- F02
- MV02
- P02
- 공통으로 사용할 수 있는 TabBar 위젯 생성
- 기존 indicatorSize 를 text -> tabs 사이즈 기준으로 변경
- 정상 동작 여부 (O)
-

feat : 공통 TabBar 위젯 생성

---

lib/widgets/loading_view.dart
lib/widgets/retry_view.dart

- 전체
- 공통으로 사용할 로딩, 새로고침 위젯 생성
- 정상 동작 여부 (O)
-

UI/view : 로딩, 새로고침 위젯

---

lib/widgets/common_toast.dart
pubspec.lock
pubspec.yaml

> ✋ PR 명명 규칙
> 
<br>
- 
<br>
- 토스트 메세지 위젯 생성
<br>
<br>
- 
<br>

[ui/toast] 커스텀 토스트 위젯 생성

---

lib/features/cart/screen/cart_screen.dart
lib/features/cart/widgets/cart total_widgets.dart
lib/features/cart/widgets/cart_bottom_bar_widgets.dart
lib/features/cart/widgets/cart_control_bar_widgets.dart
lib/features/cart/widgets/cart_empty_view_widgets.dart
lib/features/cart/widgets/cart_item_widgets.dart
lib/features/favorite/widget/favorite_gridview.dart
lib/features/goods/screen/goods_screen.dart
lib/features/movies/screen/movies_screen.dart
lib/widgets/sort_dropdown.dart
pubspec.lock
pubspec.yaml

> ✋ PR 명명 규칙
> 
<br>
- 
<br>
<br>
<br>
- merge 시 충돌로 인한 오류 수정..
<br>

[fix/provider] yaml 파일 오류 수정

---

lib/features/movies/screen/movie_detail_screen.dart

> ✋ PR 명명 규칙
> 
<br>
- 
<br>
<br>
<br>
- 
<br>

[ui/MV02] (fix)약간의 실수~ 수정

---

lib/core/router/router.dart
lib/features/login/screen/login_screen.dart
lib/features/mypage/detail/component/edit_profile_component.dart
lib/features/mypage/detail/component/fix_review_component.dart
lib/features/mypage/detail/component/my_review_component.dart
lib/features/mypage/detail/component/order_history_component.dart
lib/features/mypage/detail/my_page_detail_screen.dart
lib/features/mypage/screen/my_page_screen.dart
lib/features/signup/screen/sign_up_screen.dart
lib/widgets/review_item.dart

> ✋ PR 명명 규칙
> 
<br>
- 리뷰 아이템
<br>
리뷰아이템
사진을 누르면 다이얼로그로 큰 사진 확인
글자 수에 따라 접히고 닫히는 리뷰 텍스트
<br>
<br>
- 
<br>

[ui/R01] 리뷰 아이템 UI 구현

---

lib/core/network/kobis_client.dart
lib/core/network/tmdb_client.dart
lib/features/home/model/box_office_movie.dart
lib/features/home/model/tmdb_movie.dart
lib/features/home/repository/home_repository.dart
lib/features/home/screen/home_screen.dart
lib/features/home/service/kobis_service.dart
lib/features/home/service/tmdb_service.dart
lib/features/home/viewModel/home_viewmodel.dart
lib/features/home/widgets/best_goods_widget.dart
lib/features/home/widgets/best_movie_widget.dart
lib/features/home/widgets/box_office_ranking_widget.dart
lib/features/home/widgets/recommended_goods_widget.dart
lib/features/movies/screen/movie_detail_screen.dart
lib/main.dart
pubspec.lock
pubspec.yaml

> ✋ PR 명명 규칙
> 
<br>
- 
<br>
- TMDB & kobis API 통신 성공 및 home 화면 공통 위젯으로 변경
<br>
<br>
- 
<br>

[Feature/MOVIE-001] 

---

lib/widgets/review_item.dart

> ✋ PR 명명 규칙
> 
<br>
- 
<br>
- 기존 고정 Text 값이었던 버튼을 유동적으로 변경
<br>
<br>
-
<br>

refactor: 리뷰 아이템 버튼 고정값 변경

---

.gitignore

> ✋ PR 명명 규칙
> 
<br>
- 
<br>
- `.gitignore` 에 `.env` 추가
- 중복된 ignore 제거
<br>
<br>
<br>

[chore/add-gitignore]  chore: ignore .env file in git & remove redundant

---

lib/core/theme/app_colors.dart
lib/core/theme/app_text_style.dart
lib/features/mypage/detail/component/fix_review_component.dart
lib/features/mypage/detail/component/my_review_component.dart
lib/features/mypage/detail/component/order_detail_component.dart
lib/features/mypage/detail/component/order_history_component.dart
lib/features/mypage/detail/my_page_detail_screen.dart
lib/features/mypage/screen/my_page_screen.dart
lib/widgets/review_item.dart

> ✋ PR 명명 규칙
> 
<br>
-
<br>
-  주문 상세 내역 UI 완료
<br>
<br>
- 
<br>

[UI/r01] 주문 상세 내역 UI 

---

lib/widgets/review_item.dart

> ✋ PR 명명 규칙
> 
<br>
- 
<br>
<br>
<br>
- title 값에 따라 버튼 텍스트/표시 변경됨에 따라 리뷰 목록에서 title값으로 '리뷰 목록' 을 넘겨 주어야 합니다.
- <img src="https://github.com/user-attachments/assets/b1e20c8e-f779-4d5e-927f-173804c8c3ea" width="45%" />
<br>

[ui/review_item] fix: 리뷰 아이템 범용 사용을 위한 코드 수정

---

lib/features/goods/screen/goods_all_screen.dart

> ✋ PR 명명 규칙
> 
<br>
- g02
<br>
- read -> watch로 변경
- 기존 무한루프 통신 수정
<br>
<br>
https://www.notion.so/22a73873401a80daa3cbf3903d3a2e2a?source=copy_link
<br>

[fix/GOODS-002] read -> watch로 변경

---

lib/features/movies/model/cast_member.dart
lib/features/movies/model/tmdb_movie_detail.dart
lib/features/movies/repository/movie_detail_repository.dart
lib/features/movies/repository/movies_repository.dart
lib/features/movies/screen/movie_detail_screen.dart
lib/features/movies/screen/movies_screen.dart
lib/features/movies/service/movies_service.dart
lib/features/movies/viewmodel/movie_detail_viewmodel.dart
lib/features/movies/viewmodel/movies_viewmodel.dart
lib/features/movies/widgets/cast_grid_view.dart
lib/features/movies/widgets/cast_item.dart
lib/features/movies/widgets/movie_detail_header.dart
lib/features/movies/widgets/movie_info_row.dart
lib/main.dart
lib/widgets/common_gridview.dart

> ✋ PR 명명 규칙
> 
<br>
- MV02
<br>
- 영화 상세 페이지 데이터 통신 
- pixel 렌더링 문제 해결
- OTT 제공 아이콘 생성
<br>
<br>
- 추후 OTT 링크를 통한 사이트 연결 등 작업 필요.
- 현재 OTT 를 제공하지 않는 영화일 경우 OTT 아이콘이 나타나지 않아 MovieItem의 사이즈 문제 존재
<br>

[feat/MOVIE-004] 영화 상세 페이지 데이터 통신 

---

lib/core/model/list_response.dart
lib/core/model/pagination.dart
lib/core/model/success_response.dart
lib/features/home/model/best_goods.dart
lib/features/home/repository/best_goods_repository.dart
lib/features/home/service/best_goods_service.dart
lib/features/home/viewModel/best_goods_viewmodel.dart
lib/features/home/widgets/best_goods_widget.dart

> ✋ PR 명명 규칙
> 
<br>
- M01
<br>
- 베스트 굿즈 관련하여 목록 API 통신 후 처리 완료..
<br>
<br>
- 
<br>

[feat/GOODS-001] 베스트 굿즈 목록 서버 API 통신

---

lib/core/router/router.dart
lib/features/goods/screen/goods_review_screen.dart
lib/features/goods/widget/tabs_review.dart
lib/features/mypage/detail/my_page_detail_screen.dart
lib/features/mypage/detail/widget/fix_review_widget.dart
lib/features/mypage/detail/widget/my_review_widget.dart
lib/features/mypage/model/review.dart
lib/features/mypage/model/review_image.dart
lib/features/mypage/model/review_product.dart
lib/features/mypage/repository/review_repository.dart
lib/features/mypage/service/review_service.dart
lib/features/mypage/viewmodel/review_viewmodel.dart
pubspec.lock
pubspec.yaml

> ✋ PR 명명 규칙
> 
<br>
- R01
<br>
- 나의 리뷰 목록 조회 통신 및 리뷰 삭제 기능 구현 완료
<br>
<br>
- 리뷰 이미지를 불러올 때 현재 URL 상 오류가 있어보여 안보이는 형태..
<br>

[feat/REVIEW-002,003] 나의 리뷰 목록 조회 통신 및 리뷰 삭제 기능 구현 완료

---

lib/features/auth/service/auth_service.dart
lib/features/auth/viewmodel/sign_up_viewmodel.dart
lib/features/mypage/detail/widget/edit_profile_widget.dart
lib/features/signup/screen/sign_up_screen.dart

> ✋ PR 명명 규칙
> 
<br>
- 
<br>
<br>
<br>
- 
<br>

[fix/SIGNUP-001] 회원가입 로직수정, 회원정보 누락코드 추가

---

lib/features/goods/model/goods.dart
lib/features/goods/model/goods_images.dart
lib/features/goods/repository/goods_recommended_repository.dart
lib/features/goods/screen/goods_detail_screen.dart
lib/features/goods/services/goods_recommended_service.dart
lib/features/goods/viewmodel/goods_recommended_viewmodel.dart
lib/features/goods/widget/common_tabs_content.dart
lib/features/goods/widget/recommend_goods_widget.dart
lib/features/home/widgets/build_best_goods_grid.dart
pubspec.lock

> ✋ PR 명명 규칙
> 
<br>
- 
<br>
-  굿즈 상세 페이지 추천 굿즈 통신 및 출력 
- GoodsItem 이용
<br>
<br>
- 
<br>

[feat/GOODS-006] 굿즈 상세 페이지 추천 굿즈 통신 및 출력

---

lib/core/router/router.dart
lib/core/theme/app_text_style.dart
lib/features/mypage/detail/my_page_detail_screen.dart
lib/features/mypage/detail/widget/create_review_widget.dart
lib/features/mypage/detail/widget/order_detail_widget.dart
lib/features/mypage/detail/widget/order_history_widget.dart
lib/features/mypage/model/order/order.dart
lib/features/mypage/model/order/order_item.dart
lib/features/mypage/model/order/order_item_product.dart
lib/features/mypage/model/order/order_review.dart
lib/features/mypage/model/order/shipping_Info.dart
lib/features/mypage/model/order/status_history.dart
lib/features/mypage/model/orderdetail/detail_shipping_info.dart
lib/features/mypage/model/orderdetail/order_detail.dart
lib/features/mypage/model/orderdetail/order_detail_item.dart
lib/features/mypage/model/orderdetail/user_info.dart
lib/features/mypage/model/review_request.dart
lib/features/mypage/repository/order_detail_repository.dart
lib/features/mypage/repository/order_repository.dart
lib/features/mypage/repository/review_repository.dart
lib/features/mypage/service/order_service.dart
lib/features/mypage/service/review_service.dart
lib/features/mypage/viewmodel/order_detail_viewmodel.dart
lib/features/mypage/viewmodel/order_viewmodel.dart
lib/features/mypage/viewmodel/review_viewmodel.dart

> ✋ PR 명명 규칙
> 
<br>
- OR03
<br>
- 내 주문 내역 통신 완료 및 UI 작업 완료. router 연결
<br>
<br>
- 리뷰가 현재 있는지 체크하는 방법이 없음. -> API 요청을 통해 추후 리팩토링
<br>

[feat/ORDER-001 & DETAIL-001 & REVIEW-001] 주문 내역 통신 & 상세 주문 내역 통신 & 리뷰 작성 통신

---

lib/features/home/widgets/box_office_ranking_widget.dart

> ✋ PR 명명 규칙
> 
<br>
- 
<br>
- 박스오피스 개봉일 색상 point -> bodySmall 
<br>
<br>
- 
<br>

[refactor/MOVIE-001] 박스오피스 개봉일 날짜 색상 변경

---

lib/features/home/widgets/box_office_ranking_widget.dart

> ✋ PR 명명 규칙
> 
<br>
- M01
<br>
- 박스오피스 위젯 데이터 클릭 시 영화 상세 페이지로 이동
<br>
<br>
- 
<br>

[refactor/MOVIE-005] 박스오피스 데이터 클릭 시 영화 상세 페이지로 이동

---

lib/features/home/widgets/box_office_ranking_widget.dart

> ✋ PR 명명 규칙
> 
<br>
- 
<br>
- 홈 화면 텍스트 색상 적용 문제 해결 & ')' conflict 해결 과정에서 빠진 ) 추가
<br>
<br>
- 
<br>

[fix/MAIN-001] 홈 화면 merge 후 수정

---

lib/features/home/widgets/build_best_goods_grid.dart
lib/features/movies/model/tmdb_movie_detail.dart
lib/features/movies/repository/movie_detail_repository.dart
lib/features/movies/screen/movie_detail_screen.dart
lib/features/movies/viewmodel/movie_detail_viewmodel.dart
lib/features/movies/widgets/movie_detail_header.dart
lib/features/movies/widgets/synopsis_text.dart
pubspec.lock
pubspec.yaml

> ✋ PR 명명 규칙
> 
<br>
- 
<br>
- 탭 바 → ‘상품 ⇒ 굿즈’로 변경
- 시놉시스 더보기 기능 삭제
- 추천 굿즈 스크롤 처리 & 서버 로직 변경(?)으로 인한 처리 방식 변경
- 영화 상세 페이지 내부 OTT 아이콘 제공
- 영화 상세 페이지 Header & InfoRow 사이 간격 조절
<br>
<br>
- merge 완료 후 Cast의 defaultImage 처리 예정
<br>

[Refactor/MOVIE-004]

---

lib/features/goods/widget/header_goods_detail.dart

> ✋ PR 명명 규칙
> 
<br>
- 
<br>
<br>
<br>
- 
<br>

[fix/g02-goodsName-and-price] 굿즈명 길이, 줄 제한 & 가격, 평점의 위치 변경

---

lib/features/goods/widget/tabs_detail.dart
lib/widgets/expandable_text.dart

> ✋ PR 명명 규칙
> 
<br>
- 
<br>
<br>
<br>
- 
<br>

[fix/g02-detail] 상세설명의 길이 검증 로직 추가 및 상세설명이 없는 경우 기본값 추가

---

lib/core/storage/token_storage.dart
lib/features/cart/viewmodel/cart_viewmodel.dart
lib/features/cart/widgets/cart_bottom_bar_widgets.dart
lib/features/login/screen/login_screen.dart
lib/widgets/main_app_bar.dart

> ✋ PR 명명 규칙
> 
<br>
- 
<br>
- 로그아웃 시 장바구니 수량 표시x
- 로그인 시 장바구니 수량 표시 o
- 장바구니에서 선택 상품 없이 결제하기 클릭 시 토스트 출력
<br>
<br>
- 
<br>

[Fix/cart 001] 장바구니 수량/구매 토스트

---

lib/features/favorite/screen/favorite_screen.dart

> ✋ PR 명명 규칙
> 
<br>
- 
<br>
- 이전에 잘못 올린 파일 수정
<br>
<br>
- 
<br>

[fix/f01-f02-merge-fix] 잘못된 merge 수정

---

lib/features/movies/widgets/cast_item.dart
pubspec.lock

> ✋ PR 명명 규칙
> 
<br>
- MV02
<br>
- 출연진 네트워크 실패 시 기본 이미지 처리
<br>
<br>
- 
<br>

[fix/MV-02] 출연진 네트워크 실패 시 기본 이미지 처리

---

lib/features/goods/repository/goods_recommended_repository.dart
lib/features/goods/viewmodel/goods_recommended_viewmodel.dart
lib/features/goods/widget/recommend_goods_widget.dart

> ✋ PR 명명 규칙
> 
<br>
- 
<br>
- 굿즈 상세 페이지 추천 굿즈 오류 수정 완료
<br>
<br>
- 서버 응답값 ListResponse -> 모든 API마다 받아오는 값, 형태가 달라 null 오류, string -> int 오류 등 여러 오류가 발생하여
data만 받아오는 형태로 변경
<br>

[fix/MOVIE-002] 굿즈 상세 페이지 추천 굿즈 오류 수정 

---

lib/features/goods/screen/goods_review_screen.dart
lib/features/goods/viewmodel/goods_review_viewmodel.dart
lib/features/goods/widget/tabs_review.dart

> ✋ PR 명명 규칙
> 
<br>
- g02
<br>
- 기존 더미값이던 리뷰 이미지를 통신과 연동하였습니다.
<br>
<br>
- 
<br>

[fix/REVIEW-004] 리뷰 이미지 통신 연동

---

lib/features/goods/widget/primary_image_widget.dart
lib/features/movies/screen/movie_detail_screen.dart
lib/widgets/goods_item.dart
lib/widgets/movie_item.dart
pubspec.lock

> ✋ PR 명명 규칙
> 
<br>
- 
<br>
- 영화 상세화면에서 찜 추가 시 굿즈가 존재하지 않는 영화의 경우 에러 토스트를 출력하도록 수정하였습니다.
- 추가적으로 찜 관련 기능에서 중복적인 코드가 발생하여 goods_item에서 하나의 공통 코드로 리팩토링하였습니다.
<br>
<br>
- 
<br>

[fix/FAV-004-mv02] 영화 상세화면에서 찜 추가 시 에러 토스트 출력 (굿즈가 존재하지 않는 영화)

---

lib/features/auth/repository/auth_repository.dart
lib/features/auth/service/auth_service.dart
lib/features/auth/viewmodel/my_page_viewmodel.dart
lib/features/auth/viewmodel/sign_up_viewmodel.dart
lib/features/login/screen/login_screen.dart
lib/features/mypage/detail/my_page_detail_screen.dart
lib/features/mypage/detail/widget/edit_password_widget.dart
lib/features/mypage/detail/widget/edit_profile_widget.dart
lib/features/mypage/screen/my_page_screen.dart
lib/features/signup/screen/sign_up_screen.dart

> ✋ PR 명명 규칙
> 
<br>
[Feat/password-change]
- 
<br>
- 비밀번호 변경 UI, API 
<br>
<br>
- 
<br>

[Feat/password-change] 비밀번호 변경 UI, API 구현

---

lib/features/auth/repository/auth_repository.dart
lib/features/auth/service/auth_service.dart
lib/features/auth/viewmodel/my_page_viewmodel.dart
lib/features/auth/viewmodel/sign_up_viewmodel.dart
lib/features/login/screen/login_screen.dart
lib/features/mypage/detail/widget/edit_profile_widget.dart
lib/features/mypage/screen/my_page_screen.dart
lib/features/signup/screen/sign_up_screen.dart

> ✋ PR 명명 규칙
> 
<br>
- 
<br>
- 회원가입 API완료 및 이메일 인증 요청 값 반영
- UI 피드백 반영 (회원가입버튼)
<br>
- [] 🖼️ 스크린샷 첨부 
<br>
- 
<br>

[refactor/U01] signUp 회원가입 API, 이메일 인증 API 수정

---

lib/features/home/widgets/box_office_ranking_widget.dart
pubspec.lock
pubspec.yaml

> ✋ PR 명명 규칙
> 
<br>
- 
<br>
- boxoffice 크기 조절 및 애니메이션 처리
<br>
<br>
- 
<br>

[fix/boxoffice] boxoffice 크기 조절 및 애니메이션 처리

---

lib/features/goods/screen/goods_review_screen.dart
lib/widgets/review_item.dart

> ✋ PR 명명 규칙
> 
<br>
- r03
<br>
- isClicked 값을 통해 버튼 색상 상태 변경 및 토스트 출력
<br>
<br>
- 
<br>

[fix/REVIEW-004-effect] 굿즈 리뷰 목록 화면에서 좋아요/싫어요 이벤트 처리 강화

---

lib/core/network/api_client.dart

> ✋ PR 명명 규칙
> 
<br>
- 
<br>
- port 3000 -> 3003 으로 3팀 서버로 이동
<br>
<br>
- 
<br>

[fix/port] port 3000 -> 3003 으로 3팀 서버로 이동

---

lib/features/main/screen/main_screen.dart

> ✋ PR 명명 규칙
> 
<br>
- 
<br>
- IndexStack 으로 인해 홈 화면이 보이지 않을 경우에도 계속 상태를 유지하며 애니메이션이 동작하는 문제 
```dart
final screens = [
TickerMode(enabled: _currentIndex == 0, child: const FavoriteScreen()),
TickerMode(enabled: _currentIndex == 1, child: const GoodsAllScreen()),
TickerMode(enabled: _currentIndex == 2, child: const HomeScreen()),
TickerMode(enabled: _currentIndex == 3, child: const MoviesScreen()),
TickerMode(enabled: _currentIndex == 4, child: const MyPageScreen()),
];
```
- Flutter에서 애니메이션은 내부적으로 Ticker로 실행
- TickerMode 를 통해 애니메이션 on/off 처리
<br>
<br>
- 
<br>

[fix/lifecycle-control] IndexStack 로 인한 생명 주기 문제 해결

---

lib/features/goods/screen/goods_detail_screen.dart
pubspec.lock

> ✋ PR 명명 규칙
> 
<br>
- g02
<br>
- 공백 제거
<br>
<br>
- 
<br>

[fix/g02-tirm-delivery-refund] 배송&환불로 공백 제거

---

lib/features/goods/screen/goods_review_screen.dart
lib/features/goods/viewmodel/goods_review_viewmodel.dart

> ✋ PR 명명 규칙
> 
<br>
- g02
- r03
<br>
- 이미지 관련 로그 출력 코드 삭제
<br>
<br>
- 
<br>

[fix/logger-image-err] Logger를 통한 이미지 로그 출력 코드 삭제

---

lib/features/search/screen/search_screen.dart
lib/features/search/widgets/search_common_gridView.dart

> ✋ PR 명명 규칙
> 
<br>
- 
<br>
- searchSreen 에서 commongirdview 를 listview 안에서 사용을해 충돌 발생 해결방안으로.. search 안에 girdview 생성해 오류 수정..
<br>
<br>
- 
<br>

[Fix/search final] 검색 진짜 최종본

---

lib/features/mypage/detail/widget/order_detail_widget.dart

> ✋ PR 명명 규칙
> 
<br>
- 
<br>
- 주문 상세 내역 -> 버튼 비활성화 느낌으로 변경
- 토스트 삭제
- 주문자 정보, 결제 정보 디자인 수정
<br>
<br>
- 
<br>

[fix/order_detail] 주문 상세 버튼 -> 비활성화로 변경

---

lib/features/goods/screen/goods_all_screen.dart
lib/features/goods/viewmodel/goods_all_viewmodel.dart
pubspec.lock

> ✋ PR 명명 규칙
> 
<br>
- g01
<br>
- 전체 굿즈 조회 시 페이징 처리
<br>
<br>
- 
<br>

[fix/goods-002-paging] 전체 굿즈 조회 시 페이징 처리

---

lib/features/favorite/screen/favorite_screen.dart
lib/features/favorite/viewmodel/favorite_viewmodel.dart
lib/widgets/goods_item.dart
lib/widgets/movie_item.dart

> ✋ PR 명명 규칙
> 
<br>
- f01
- f02
<br>
- 찜 토글 시의 토스트 텍스트 수정
- 영화 찜이 없는 경우 대체  화면 출력
<br>
<br>
- 
<br>

[fix/fav-toast-movie-empty-screen] 찜 토글 시의 토스트 텍스트 수정 및 영화 찜이 없는 경우 대체  화면 출력

---

lib/features/mypage/screen/my_page_screen.dart

> ✋ PR 명명 규칙
> 
<br>
- 닉네임+이메일 flexible 로 감싸기
<br>
<br>
<br>
- 
<br>

[fix/mypage_screen_email] 이메일 픽셀 짤림

---

lib/features/mypage/detail/widget/order_history_widget.dart

> ✋ PR 명명 규칙
> 
<br>
- 
<br>
- 배송 추적 -> 주문 내역은 배송 완료된 것만 보이게끔 수정
<br>
<br>
- 
<br>

[fix/order_tracking] 배송 추적 -> 주문 내역은 배송 완료된 것만 보이게끔 수정

---

lib/features/goods/screen/goods_review_screen.dart
lib/widgets/review_item.dart

> ✋ PR 명명 규칙
> 
<br>
- r03
<br>
- 좋아요 시 모든 리뷰에 좋아요 처리되는 문제 해결
- 좋아요 / 싫어요가 동시에 가능한 문제 수정
- 사용자의 클릭에 따른 좋아요 count 숨김
<br>
<br>
- 
<br>

[fix/r03-like-dislike] 리뷰의 좋아요 / 싫어요 출력 수정

---

lib/features/auth/viewmodel/auth_provider.dart
lib/features/auth/viewmodel/login_viewmodel.dart
lib/features/favorite/screen/favorite_screen.dart
lib/features/goods/screen/goods_all_screen.dart
lib/features/home/screen/home_screen.dart
lib/features/login/screen/login_screen.dart
lib/features/main/screen/main_screen.dart
lib/features/movies/screen/movies_screen.dart
lib/features/mypage/screen/my_page_screen.dart
lib/main.dart

> ✋ PR 명명 규칙
> 
<br>
- 
<br>
<br>
<br>
- 하다 막혀 AI 도움받았습니다. 아직 이해하지 못한 상태이므로 질문은 정중히 사양합니다.
<br>

[fix/after_login] 로그인/로그아웃 시 Provider 갱신

---

lib/core/network/api_client.dart

> ✋ PR 명명 규칙
> 
<br>
- 
<br>
- API 요청 중 accessToken이 만료되었을 때(403 + "Invalid or expired token"),
refreshToken을 사용하여 accessToken을 자동으로 재발급하고
실패 시 로그아웃 처리하는 로직을 추가
1. 요청 실패 시 onError 인터셉터에서 상태 코드 403 + 특정 메시지를 확인
2. TokenStorage에서 저장된 refreshToken을 불러와 /api/auth/refresh 요청
3. 재발급 성공 시 새로운 accessToken을 저장하고, 기존 요청을 그대로 재시도
4. 재발급 실패 시 토큰을 초기화하고 에러 처리 → 로그아웃 유도
<br>
<br>
- 
<br>

[fix/refreshToken] refreshToken 처리
